-- TABLAS PRINCIPALES

-- 1. Generadores
CREATE TABLE IF NOT EXISTS public.generadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    nodo TEXT NOT NULL,
    serial TEXT UNIQUE, -- Added UNIQUE constraint
    potencia NUMERIC, -- Changed to NUMERIC
    estado TEXT DEFAULT 'OFF',
    voltaje NUMERIC, -- Changed to NUMERIC
    corriente NUMERIC, -- Changed to NUMERIC
    frecuencia NUMERIC, -- Changed to NUMERIC
    combustible NUMERIC DEFAULT 0,
    bateria NUMERIC, -- Changed to NUMERIC
    horas_motor NUMERIC, -- Changed to NUMERIC
    alarmas TEXT[] DEFAULT '{}',
    ultima_lectura TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW() -- New column
);

-- 2. Escaneos
CREATE TABLE IF NOT EXISTS public.escaneos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial TEXT,
    texto_ocr TEXT,
    json_extraido JSONB,
    confianza NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Eventos
CREATE TABLE IF NOT EXISTS public.eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial TEXT,
    generador_nombre TEXT,
    operador TEXT,
    tipo TEXT NOT NULL,
    litros NUMERIC,
    nivel_resultante NUMERIC,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- HABILITAR REALTIME
ALTER PUBLICATION supabase_realtime ADD TABLE generadores;
ALTER PUBLICATION supabase_realtime ADD TABLE escaneos;
ALTER PUBLICATION supabase_realtime ADD TABLE eventos;

-- STORAGE BUCKETS
-- (Nota: Estos se crean usualmente via UI o API, pero aquí definimos la estructura)
-- Bucket: 'capturas'
-- Public read access can be enabled via RLS on storage.objects

-- RLS POLICIES (Básicas para desarrollo)
ALTER TABLE public.generadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escaneos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read for authenticated users" ON public.generadores FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow public read for authenticated users" ON public.escaneos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow public read for authenticated users" ON public.eventos FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow updates for authenticated users" ON public.generadores FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow inserts for authenticated users" ON public.generadores FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow deletes for authenticated users" ON public.generadores FOR DELETE TO authenticated USING (true);
CREATE POLICY "Allow inserts for authenticated users" ON public.escaneos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow inserts for authenticated users" ON public.eventos FOR INSERT TO authenticated WITH CHECK (true);
